/* ============================================================================
 * 09_kabiKpiLibrary.js  —  KABi Enterprise KPI Library (2026, career-enhanced)
 * ----------------------------------------------------------------------------
 * Authoritative "Priority 1" KPI source for the KPI Architect agent.
 * From: KABi_Enterprise_KPI_Library_2026_Career_Enhanced.xlsx → sheet "KPI Library".
 * 696 level-specific KPIs total (29 functions × 4 library levels L1–L4 × ~6).
 *
 * PILOT SCOPE: bd-sales (Business Development, 24 KPIs). Prove the pipeline here,
 * then extend the RAW array to the other 28 functions.
 *
 * Each KPI is level-tailored: same 6 metrics per function but the SMART template,
 * scope, career track and decision rights change by level (L1 individual tasks →
 * L2 owned workstream → L3 team/process → L4 enterprise strategy). Targets stay
 * manager-defined ({TARGET}/{PERIOD} placeholders).
 *
 * The 5 display tiers map onto the 4 library levels:
 *   Entry→L1 · Intermediate→L2 · First-level management→L3 · Advanced/Executive→L4
 *
 * Load AFTER index.html (like 06/07):  <script src="09_kabiKpiLibrary.js"></script>
 * ==========================================================================*/
(function () {
  'use strict';
  if (typeof window === 'undefined' || !window.KABi) {
    console.warn('[KPI Library] KABi namespace not found — load after index.html');
    return;
  }
  var KABi = window.KABi;

  // Excel "Function" label → app fnKey (extend as more functions are ingested).
  var FN_LABEL_TO_KEY = { 'Business Development': 'bd-sales' };

  // Raw rows (essential fields) for the pilot function.
  var RAW = [
    { fn:'bd-sales', id:'SEL-BDD-L1-01', lvl:'L1', cat:'Leading', rec:'Core', name:'Qualified Pipeline Coverage', smart:'By {PERIOD}, maintain Qualified Pipeline Coverage at or above {TARGET} across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, calculated from CRM / approved sales target using the approved attribution and scope.', formula:'Approved qualified open pipeline value ÷ approved revenue target for the same period', unit:'ratio', dir:'Higher', cadence:'Monthly', source:'CRM / approved sales target', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L1-02', lvl:'L1', cat:'Leading', rec:'Optional', name:'Planned Commercial Activity Completion', smart:'By {PERIOD}, achieve at least {TARGET}% for Planned Commercial Activity Completion across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, measured using the approved formula and CRM / calendar / sales engagement platform.', formula:'Approved commercial activities completed by due date ÷ approved commercial activities due × 100', unit:'%', dir:'Higher', cadence:'Weekly', source:'CRM / calendar / sales engagement platform', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L1-03', lvl:'L1', cat:'Process', rec:'Core', name:'Proposal Turnaround Time', smart:'By {PERIOD}, maintain Proposal Turnaround Time at or below {TARGET} days across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, measured from approved start and completion timestamps in CRM / proposal repository / bid tracker.', formula:'Median business days from complete approved request to approved proposal issuance or bid submission', unit:'days', dir:'Lower', cadence:'Monthly', source:'CRM / proposal repository / bid tracker', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L1-04', lvl:'L1', cat:'Process', rec:'Optional', name:'Sales Cycle Length', smart:'By {PERIOD}, maintain Sales Cycle Length at or below {TARGET} days across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, measured from approved start and completion timestamps in CRM.', formula:'Median calendar days from approved qualification date to final opportunity close date', unit:'days', dir:'Lower', cadence:'Quarterly', source:'CRM', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L1-05', lvl:'L1', cat:'Lagging', rec:'Core', name:'Closed-Won Revenue Target Attainment', smart:'By {PERIOD}, achieve at least {TARGET}% for Closed-Won Revenue Target Attainment across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, measured using the approved formula and CRM / finance validation.', formula:'Approved closed-won revenue ÷ approved closed-won revenue target × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM / finance validation', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L1-06', lvl:'L1', cat:'Health', rec:'Core', name:'Revenue Forecast Accuracy', smart:'By {PERIOD}, achieve at least {TARGET}% for Revenue Forecast Accuracy across assigned prospect follow-ups, meeting preparation, CRM updates, proposal inputs, and bid tasks, measured using the approved formula and CRM forecast / finance actuals.', formula:'100 - absolute value of forecast revenue - actual revenue ÷ actual revenue × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM forecast / finance actuals', track:'Common foundation (pre-track)', decision:'Executes defined work using approved procedures; escalates exceptions and depends on review for high-risk decisions.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-01', lvl:'L2', cat:'Leading', rec:'Core', name:'Qualified Pipeline Coverage', smart:'By {PERIOD}, maintain Qualified Pipeline Coverage at or above {TARGET} across an owned opportunity, account segment, bid, or territory, calculated from CRM / approved sales target using the approved attribution and scope.', formula:'Approved qualified open pipeline value ÷ approved revenue target for the same period', unit:'ratio', dir:'Higher', cadence:'Monthly', source:'CRM / approved sales target', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-02', lvl:'L2', cat:'Leading', rec:'Optional', name:'Planned Commercial Activity Completion', smart:'By {PERIOD}, achieve at least {TARGET}% for Planned Commercial Activity Completion across an owned opportunity, account segment, bid, or territory, measured using the approved formula and CRM / calendar / sales engagement platform.', formula:'Approved commercial activities completed by due date ÷ approved commercial activities due × 100', unit:'%', dir:'Higher', cadence:'Weekly', source:'CRM / calendar / sales engagement platform', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-03', lvl:'L2', cat:'Process', rec:'Core', name:'Proposal Turnaround Time', smart:'By {PERIOD}, maintain Proposal Turnaround Time at or below {TARGET} days across an owned opportunity, account segment, bid, or territory, measured from approved start and completion timestamps in CRM / proposal repository / bid tracker.', formula:'Median business days from complete approved request to approved proposal issuance or bid submission', unit:'days', dir:'Lower', cadence:'Monthly', source:'CRM / proposal repository / bid tracker', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-04', lvl:'L2', cat:'Process', rec:'Optional', name:'Sales Cycle Length', smart:'By {PERIOD}, maintain Sales Cycle Length at or below {TARGET} days across an owned opportunity, account segment, bid, or territory, measured from approved start and completion timestamps in CRM.', formula:'Median calendar days from approved qualification date to final opportunity close date', unit:'days', dir:'Lower', cadence:'Quarterly', source:'CRM', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-05', lvl:'L2', cat:'Lagging', rec:'Core', name:'Closed-Won Revenue Target Attainment', smart:'By {PERIOD}, achieve at least {TARGET}% for Closed-Won Revenue Target Attainment across an owned opportunity, account segment, bid, or territory, measured using the approved formula and CRM / finance validation.', formula:'Approved closed-won revenue ÷ approved closed-won revenue target × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM / finance validation', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L2-06', lvl:'L2', cat:'Health', rec:'Core', name:'Revenue Forecast Accuracy', smart:'By {PERIOD}, achieve at least {TARGET}% for Revenue Forecast Accuracy across an owned opportunity, account segment, bid, or territory, measured using the approved formula and CRM forecast / finance actuals.', formula:'100 - absolute value of forecast revenue - actual revenue ÷ actual revenue × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM forecast / finance actuals', track:'Common professional foundation (track emerging)', decision:'Owns end-to-end delivery within delegated authority; diagnoses issues, recommends improvements, and manages routine stakeholders.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-01', lvl:'L3', cat:'Leading', rec:'Core', name:'Qualified Pipeline Coverage', smart:'By {PERIOD}, maintain Qualified Pipeline Coverage at or above {TARGET} across a business-development team, opportunity portfolio, and commercial process, calculated from CRM / approved sales target using the approved attribution and scope.', formula:'Approved qualified open pipeline value ÷ approved revenue target for the same period', unit:'ratio', dir:'Higher', cadence:'Monthly', source:'CRM / approved sales target', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-02', lvl:'L3', cat:'Leading', rec:'Optional', name:'Planned Commercial Activity Completion', smart:'By {PERIOD}, achieve at least {TARGET}% for Planned Commercial Activity Completion across a business-development team, opportunity portfolio, and commercial process, measured using the approved formula and CRM / calendar / sales engagement platform.', formula:'Approved commercial activities completed by due date ÷ approved commercial activities due × 100', unit:'%', dir:'Higher', cadence:'Weekly', source:'CRM / calendar / sales engagement platform', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-03', lvl:'L3', cat:'Process', rec:'Core', name:'Proposal Turnaround Time', smart:'By {PERIOD}, maintain Proposal Turnaround Time at or below {TARGET} days across a business-development team, opportunity portfolio, and commercial process, measured from approved start and completion timestamps in CRM / proposal repository / bid tracker.', formula:'Median business days from complete approved request to approved proposal issuance or bid submission', unit:'days', dir:'Lower', cadence:'Monthly', source:'CRM / proposal repository / bid tracker', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-04', lvl:'L3', cat:'Process', rec:'Optional', name:'Sales Cycle Length', smart:'By {PERIOD}, maintain Sales Cycle Length at or below {TARGET} days across a business-development team, opportunity portfolio, and commercial process, measured from approved start and completion timestamps in CRM.', formula:'Median calendar days from approved qualification date to final opportunity close date', unit:'days', dir:'Lower', cadence:'Quarterly', source:'CRM', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-05', lvl:'L3', cat:'Lagging', rec:'Core', name:'Closed-Won Revenue Target Attainment', smart:'By {PERIOD}, achieve at least {TARGET}% for Closed-Won Revenue Target Attainment across a business-development team, opportunity portfolio, and commercial process, measured using the approved formula and CRM / finance validation.', formula:'Approved closed-won revenue ÷ approved closed-won revenue target × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM / finance validation', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L3-06', lvl:'L3', cat:'Health', rec:'Core', name:'Revenue Forecast Accuracy', smart:'By {PERIOD}, achieve at least {TARGET}% for Revenue Forecast Accuracy across a business-development team, opportunity portfolio, and commercial process, measured using the approved formula and CRM forecast / finance actuals.', formula:'100 - absolute value of forecast revenue - actual revenue ÷ actual revenue × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM forecast / finance actuals', track:'Leadership or Technical', decision:'Sets operating priorities, allocates resources, coaches others, manages dependencies and risks, and is accountable for team outcomes.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-01', lvl:'L4', cat:'Leading', rec:'Core', name:'Qualified Pipeline Coverage', smart:'By {PERIOD}, maintain Qualified Pipeline Coverage at or above {TARGET} across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, calculated from CRM / approved sales target using the approved attribution and scope.', formula:'Approved qualified open pipeline value ÷ approved revenue target for the same period', unit:'ratio', dir:'Higher', cadence:'Monthly', source:'CRM / approved sales target', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-02', lvl:'L4', cat:'Leading', rec:'Optional', name:'Planned Commercial Activity Completion', smart:'By {PERIOD}, achieve at least {TARGET}% for Planned Commercial Activity Completion across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, measured using the approved formula and CRM / calendar / sales engagement platform.', formula:'Approved commercial activities completed by due date ÷ approved commercial activities due × 100', unit:'%', dir:'Higher', cadence:'Weekly', source:'CRM / calendar / sales engagement platform', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-03', lvl:'L4', cat:'Process', rec:'Core', name:'Proposal Turnaround Time', smart:'By {PERIOD}, maintain Proposal Turnaround Time at or below {TARGET} days across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, measured from approved start and completion timestamps in CRM / proposal repository / bid tracker.', formula:'Median business days from complete approved request to approved proposal issuance or bid submission', unit:'days', dir:'Lower', cadence:'Monthly', source:'CRM / proposal repository / bid tracker', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-04', lvl:'L4', cat:'Process', rec:'Optional', name:'Sales Cycle Length', smart:'By {PERIOD}, maintain Sales Cycle Length at or below {TARGET} days across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, measured from approved start and completion timestamps in CRM.', formula:'Median calendar days from approved qualification date to final opportunity close date', unit:'days', dir:'Lower', cadence:'Quarterly', source:'CRM', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-05', lvl:'L4', cat:'Lagging', rec:'Core', name:'Closed-Won Revenue Target Attainment', smart:'By {PERIOD}, achieve at least {TARGET}% for Closed-Won Revenue Target Attainment across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, measured using the approved formula and CRM / finance validation.', formula:'Approved closed-won revenue ÷ approved closed-won revenue target × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM / finance validation', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' },
    { fn:'bd-sales', id:'SEL-BDD-L4-06', lvl:'L4', cat:'Health', rec:'Core', name:'Revenue Forecast Accuracy', smart:'By {PERIOD}, achieve at least {TARGET}% for Revenue Forecast Accuracy across the enterprise growth strategy, strategic-deal portfolio, market expansion, and commercial economics, measured using the approved formula and CRM forecast / finance actuals.', formula:'100 - absolute value of forecast revenue - actual revenue ÷ actual revenue × 100', unit:'%', dir:'Higher', cadence:'Monthly', source:'CRM forecast / finance actuals', track:'Leadership or Technical', decision:'Sets strategy, governance, investment priorities and enterprise standards; owns long-term value, risk and sustainability.' }
  ];

  // Build index: data[fnKey][levelCode] = [kpi, ...]
  var data = {};
  RAW.forEach(function (k) {
    (data[k.fn] = data[k.fn] || {});
    (data[k.fn][k.lvl] = data[k.fn][k.lvl] || []).push(k);
  });

  KABi.KpiLibrary = {
    fnLabelToKey: FN_LABEL_TO_KEY,
    data: data,
    // 5 display tiers → 4 library level codes
    tierToLevelCode: {
      'Entry': 'L1',
      'Intermediate': 'L2',
      'First-level management': 'L3',
      'Advanced': 'L4',
      'Executive': 'L4'
    },
    has: function (fnKey) { return !!this.data[fnKey]; },
    // All library KPIs for a function at a given display tier (or level code).
    get: function (fnKey, tierOrCode) {
      var fn = this.data[fnKey];
      if (!fn) return [];
      var code = this.tierToLevelCode[tierOrCode] || (fn[tierOrCode] ? tierOrCode : 'L1');
      return fn[code] || [];
    },
    // Core-only (the recommended backbone set).
    getCore: function (fnKey, tierOrCode) {
      return this.get(fnKey, tierOrCode).filter(function (k) { return k.rec === 'Core'; });
    }
  };

  console.log('[KPI Library] loaded:', Object.keys(data).map(function (f) {
    return f + '(' + Object.keys(data[f]).length + ' levels)';
  }).join(', '));
})();
